services:
  aws-api-gateway-simulator:
    image: node:18-alpine
    container_name: local-aws-api-simulator
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
        npm install express cors &&
        node server.js
      "
    ports:
      - "3000:3001"
    volumes:
      - ./api-gateway-simulator:/app
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - sam-local-network

  aws-sam-local:
    image: public.ecr.aws/sam/build-nodejs18.x:latest
    container_name: local-aws-sam-cli
    restart: unless-stopped
    working_dir: /var/task
    command: >
      bash -c "
        echo 'SAM CLI starting...' &&
        sam --version &&
        echo 'Validating template...' &&
        sam validate &&
        echo 'Installing dependencies...' &&
        cd src/hello-world && npm install && cd ../.. &&
        cd src/health && npm install && cd ../.. &&
        echo 'Starting SAM Local API Gateway...' &&
        sam local start-api --host 0.0.0.0 --port 3002 --skip-pull-image
      "
    ports:
      - "3002:3002"
    volumes:
      - ./aws-sam-local:/var/task
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SAM_CLI_TELEMETRY=0
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy-key
      - AWS_SECRET_ACCESS_KEY=dummy-secret
    networks:
      - sam-local-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/hello"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 180s

networks:
  sam-local-network:
    driver: bridge
