apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: local-dev
data:
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:30092
  KAFKA_BROKER_ID: "1"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: local-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: local-dev
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: local-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        envFrom:
        - configMapRef:
            name: kafka-config
        ports:
        - containerPort: 9092
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - kafka-broker-api-versions --bootstrap-server localhost:9092
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: local-dev
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 30092
  type: NodePort
