# MuleSoft Anypoint Flex Gateway Local Mode Registration
# This configuration runs Flex Gateway in local mode for development and testing

# Local mode configuration - no Anypoint Platform connection required
gatewayId: "local-flex-gateway"
gatewayName: "Local Development Gateway"
mode: "local"

# Local runtime configuration
runtime:
  # Enable local mode
  localMode: true
  
  # Gateway runtime settings
  server:
    host: "0.0.0.0"
    port: 8080
    
  # Management port for health checks and metrics
  management:
    host: "0.0.0.0"
    port: 8081
    
# Logging configuration
logging:
  level: INFO
  format: json
  
# Health check configuration
healthCheck:
  enabled: true
  path: "/health"
  
# Metrics configuration  
metrics:
  enabled: true
  path: "/metrics"
